name: unit-tests
run-name: Run unit tests after push by @${{ github.actor }}
on:
  push:
    branches: [ master ]
jobs:
  unit-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os : [ubuntu-latest]
        python-version: [ "3.9" ]
    env:
      DISPLAY: ':99.0'
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Install Qt
        uses: tlambert03/setup-qt-libs@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Start Xvfb
        run: |
          sudo apt-get install -y xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sudo apt install -y xvfb x11-utils libxkbcommon-x11-0
          sudo apt-get install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev
          pip install wheel
          pip install -r requirements.txt
          sudo pip install PyQt6
          sudo pip install pytest
          
          

      - name: Check job values
        run: |
          QT_SELECT=qt6

      - name: Test with pytest
        run: |
          sudo pytest


      
